### ISSUE TITLE
take off text bg color

### ISSUE THREAD

**Issue by splatalina** [splatalina/languid.biz.website#2]
i dont like it anymore but its confusing me how to change it back

**Comment by Simonmoush** [comment]
I moved the style information to the stylesheet (style.css) and I tagged the headings with classes and in the two unique cases with ids. Those are referenced in the style sheet (.class and #id) and the styles listed there will apply to the matching elements of the HTML file. so you can change a bunch of elements at once by tagging them all with the same class. check out the stylesheet. delete the background-color where you don't want it.

**Comment by splatalina** [comment]
o cool i get it!
