### ISSUE TITLE
Draw a random tarot card

### ISSUE THREAD

**Issue by splatalina** [splatalina/languid.biz.website#4]
can i put a button where when you click it you get a random number between 1 and 5

**Comment by Simonmoush** [comment]
issues should be more like stating a goal or a vision. or fixing a bug or problem. can u put the whole vision for why u want it and what you want to happen on the site? A random number generator might not even be necessary or part of the solution

**Comment by splatalina** [comment]
I'd like the page oracle.html to have this image be a button:

https://i.imgur.com/8iTh6Vr.png

and when you click it, a random one of these five images will appear

1. https://i.imgur.com/jNyssUX.jpeg
2.  https://i.imgur.com/NJFyO1U.jpeg
3. https://i.imgur.com/JpH9sb7.jpeg
4. https://i.imgur.com/xHET3k6.jpeg
5. https://i.imgur.com/TwY7XJP.jpeg

once one of these 5 images randomly appears, I want a link beneath it to appear to go to a new web page where you can learn more about the image that has appeared. each image will have a web page that it links to where it will show the image + text about the image I will add to the page 

The image webpages could be 

1. two-buds.html
2. washing-machine.html
3. beetle.html
4. fig.html
5. necklace.html

**Comment by splatalina** [comment]
I suppose I'm not sure if the image explainer text should/could appear with the image when the oracle button is pushed instead?

**Comment by splatalina** [comment]
I edited the above to reflect that I want a "Learn more about this card (or something like that)" text link to the tarot explainer webpage instead of having the tarot image itself be the link!

**Comment by Simonmoush** [comment]
booooooom done
